services:
  - type: web
    name: golf-skin-games
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    autoDeployTrigger: commit
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: public
      - key: PUBLIC_DB_DIR
        value: /tmp/scorecard-db
