spring.jpa.hibernate.ddl-auto=updata
spring.datasource.url=jdbc:hsqldb:file:./data/hsqldb/devdb

logging.level.org.springframework.web=ERROR
logging.level.fi.mlappi=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

spring.profiles.active=postgres
#spring.profiles.active=render

admin.username=admin
admin.password=admin123
