# PostgreSQL datasource for Docker
# Activate with `-Dspring.profiles.active=postgres` or set `SPRING_PROFILES_ACTIVE=postgres` in environment

#spring.datasource.url=jdbc:postgresql://dpg-d58m07ggjchc73a8lctg-a.frankfurt-postgres.render.com/golf_xwj5
#spring.datasource.url=jdbc:postgresql://dpg-d58m07ggjchc73a8lctg-a/golf_xwj5

#spring.datasource.username=${POSTGRES_USER:golf}
#spring.datasource.password=${POSTGRES_PASSWORD:BM0rlWdDSW72tl93DkcjiFaqbXUcLI5r}
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:hsqldb:file:./data/hsqldb/devdb

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=1
